version: '3'

services:
  # server:
  #   build: .
  #   ports:
  #     - '3000:3000'
  #   depends_on:
  #     - db
  #   env_file:
  #     - .env.production
  # redis:
  #   container_name: admin_session_redis
  #   image: redis:latest
  #   ports:
  #     - '6379:6379'
  db:
    container_name: admin_session_db
    image: mysql:5.7
    restart: always
    ports:
      - 3308:3306
    volumes:
      - db_volume:/var/lib/mysql
    environment:
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: nest_db_session
      TZ: Asia/Seoul
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  phpmyadmin:
    container_name: admin_session_phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=password
      - PMA_ARBITRARY=1
volumes:
  db_volume:
